### PR TITLE
Custom provider factory

### PR DESCRIPTION
**Pull request by mauroservienti**
When integrating with ASP.Net Core it's mandatory that the service provider instance it's shared across NServiceBus and the .NET Core runtime. To do so the NServiceBus used container, as it is the one created first, needs to be returned from the `ConfigureServices` method, e.g.:

```
public IServiceProvider ConfigureServices(IServiceCollection services)
{
   //create the container wrapping the services collection
   //return the container instance
}
```

To allow the above approach users need to be able to inject a custom service provider factory so to have full control over the container instance creation. This PR contains a very draft/raw set of changes to:

- expose the `UpdatableServiceProvider` class to users code
- introduce a `ServiceProviderFactory` configuration extension

The end goal is to be able to write something like:

```
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    services.AddSignalR();
    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

    IEndpointInstance endpointInstance = null;
    services.AddSingleton<IMessageSession>(_ => endpointInstance);

    var ec = new EndpointConfiguration("NServiceBusSignalRCallback");
    ec.UseTransport<LearningTransport>();

    UpdateableServiceProvider container = null;
    ec.UseContainer<ServicesBuilder>(c =>
    {
        c.ExistingServices(services);
        c.ServiceProviderFactory(sc => 
        {
            container = new UpdateableServiceProvider(sc);
            return container;
        });
    });

    endpointInstance = Endpoint.Start(ec).GetAwaiter().GetResult();

    return container;
}
```

With the above code NServiceBus and .NET Core share the same container instance and bi-directional resolution of components works as expected. More details on the problem this attempts to solve are available in this thread: https://discuss.particular.net/t/support-for-microsoft-extensions-dependencyinjection/129

@twenzel the current implementation is just a way to demonstrate the need, feel free to rework this PR as you prefer. If you have any questions, please, do not hesitate to ping me.

### CODE REVIEW

**Comment by mauroservienti** [comment]
@twenzel any news on this?

**Comment by twenzel** [comment]
Let me thought about this. I should test this with scenarios where another DI container is used (e.g. Autofac or Windsor Castle).

**Comment by simonpinn** [comment]
Hey @twenzel any update on this, I've recently run up against the same issue! It's killing me that I'll likely need to pull autofac in just to bridge the DI gap.
thanks

**Comment by twenzel** [comment]
I would change this PR to be backward compatible.

**Comment by twenzel** [comment]
@mauroservienti Can you update this PR to be backward compatible and that the solution can be build and all tests are running.
I'm fine with the approach that the service provider can be exposed.

**Comment by mauroservienti** [comment]
PR updated. Tests are now aligned with the new API. Locally they are all green, waiting for AppVeyor.

**Comment by mauroservienti** [comment]
I'm not sure I like the idea of exposing the `UpdateableServiceProvider` as is, mine is more of a hack to show the problem. Anyway feel free to change this PR as you will or cherry pick.

**Comment by simonpinn** [comment]
Thanks @twenzel and @mauroservienti !
The concept is now a lot closer to how NSB with Autofac works, with a `IServiceProvider` being created by the Autofac integration, for example:
```
            var container = containerBuilder.Build();

            endpointConfiguration.UseContainer<AutofacBuilder>(
                customizations: customizations =>
                {
                    customizations.ExistingLifetimeScope(container);
                });

            endpoint = Endpoint.Start(endpointConfiguration)
                .ConfigureAwait(false).GetAwaiter().GetResult();

            return new AutofacServiceProvider(container);
```
Exposing the `UpdateableServiceProvider` is a similar concept, so I'm personally ok with this

**Comment by simonpinn** [comment]
I can also confirm this approach works with `IHubContext`

Using this branch it gets me down to a neat one-liner here:
https://github.com/Rockend/property-management/blob/master/src/server/PropertyManagement.Service/Startup.cs#L45

When using:
https://github.com/Rockend/Rockend.Nsb/blob/master/src/Rockend.Nsb/RockendNsbInjectionExtensions.cs#L75

Hope to see it merged!

**Comment by sungam3r** [comment]
I also ran into NServiceBus DI integration issues.

Yes, this PR solves some of the problems, but not all. This approach is tailored for the specific use of ASP.NET Core, which allows you to have the desired method signature (returning `IServiceProvider`). The first thing that seems wrong to me is the **early creation** of `endpointInstance`. It should be created on demand at a time when it is really needed. Secondly, the creation of `IServiceProvider` actually prohibits the use of a similar package, which would also require the creation of `IServiceProvider ` by analogy with NServiceBus. Only one must win.

The conceptual problem is that NServiceBus DI integration should only fill `IServiceCollection` accordingly, and **not try to build it**. This is responsibility of a hosting environment (ASP.NET Core, Generic Host, whatever). Now integration with various DI containers is quite complicated and confusing.

**Comment by mauroservienti** [comment]
You’re correct @sungam3r, up to version 7.1 NServiceBus starts from the assumption that it owns the container. This expected ownership is what’s causing all the troubles with Asp.Net Core, and is what is forcing the creation of the endpoint instance in the “wrong” place during the Asp.Net Core startup phase. We currently in the process of lifting that constraint with the goal of becoming good citizens in the Asp.Net Core ecosystem. I’m not sure when we’ll be ready with the release and if it’ll make it for 7.2 but the train left the station and is in motion.

**Comment by sungam3r** [comment]
I suspect that this may require rethinking DI integration API in NServiceBus itself.

**Comment by mauroservienti** [comment]
Luckily it seems to be way simpler. We’ve already run investigations and spikes and realized that over the years the internal DI mechanism evolved in such a way that the aforementioned “ownership” is not anymore that required. This allows to split the initialization phase from the startup and runtime phases. Obviously what’s missing is the public API required for the integration with IServiceCollection.

**Comment by sungam3r** [comment]
I am glad to hear this.

**Comment by sungam3r** [comment]
@mauroservienti  Hi. I just looked at the source code for NServiceBus and NServiceBus.MSDependencyInjection. Honestly, I can’t imagine how to solve the problem without significant changes. I see that in NServiceBus code, the registration of dependencies is smeared by the code already in the process of its execution. That is, it is assumed that the container is updated in the process of its work. This is a rather serious complication of the system as a whole.

In addition, I saw that in the `UpdateableServiceProvider` code of NServiceBus.MSDependencyInjection project, the `IServiceProvider` is rebuilt every time the `ServiceCollection` is changed, but this for some reason does not happen in the `Insert` and `RemoveAt` methods.

In addition, I am **very surprised** that the old `ServiceProvider` is not destroyed during the upgrade. If there were disposable resources, then their destruction will not be caused.

**Now I don’t understand how all this can work stably?**

**Comment by mauroservienti** [comment]
I've been involved in the original planning of the feature. The implementation is ongoing now, here is the PR that changes NServiceBus to enable `IServiceCollection` integration: https://github.com/Particular/NServiceBus/pull/5411

The Core PR introduces the concept of `PreparedEndpoint`, a prepared endpoint is a not yet started but configured endpoint that doesn't require full control over a DI container.

The [corresponding doco PR](https://github.com/Particular/docs.particular.net/pull/4475) with a small sample on how Core changes can be used to effectively integrate with `IServiceCollection`

**Comment by mauroservienti** [comment]
@sungam3r we're progressing on the implementation, here is the [documentation](https://docs.particular.net/nservicebus/dependency-injection/?version=core_7.2#externally-managed-mode) and the [samples](https://docs.particular.net/samples/dependency-injection/aspnetcore/)

**Pull request merged**
